# Generated by Django 5.0.4 on 2024-05-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lojaMiniaturas_app", "0002_alter_imagem_produto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="data_cadastro",
            field=models.DateField(auto_now_add=True),
        ),
    ]
