# Generated by Django 5.0.4 on 2024-04-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lojaMiniaturas_app", "0002_boneca_carro_funkopop_delete_produtos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=6)),
                ("descricao", models.TextField()),
                ("codigo", models.IntegerField()),
                ("categoria", models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name="Boneca",
        ),
        migrations.DeleteModel(
            name="Carro",
        ),
        migrations.DeleteModel(
            name="FunkoPop",
        ),
    ]
