# Generated by Django 5.0.4 on 2024-04-19 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lojaMiniaturas_app", "0002_alter_imagem_produto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagem",
            name="produto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imagens",
                to="lojaMiniaturas_app.produto",
            ),
        ),
    ]
