# Generated by Django 5.0.4 on 2024-04-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "lojaMiniaturas_app",
            "0003_produto_delete_boneca_delete_carro_delete_funkopop",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="imagem",
            field=models.TextField(null=True),
        ),
    ]
