# Generated by Django 5.0.4 on 2024-04-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaMiniaturas_app', '0003_alter_imagem_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
