# Generated by Django 5.0.4 on 2024-04-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lojaMiniaturas_app", "0004_produto_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="imagem",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
