# Generated by Django 5.0.4 on 2024-04-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lojaMiniaturas_app", "0005_alter_produto_imagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Imagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("imagem", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="produto",
            name="imagem",
        ),
    ]
