# Generated by Django 5.0.4 on 2024-04-12 22:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lojaMiniaturas_app", "0006_imagem_remove_produto_imagem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagem",
            name="imagem",
        ),
    ]
