# Generated by Django 5.0.4 on 2024-04-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lojaMiniaturas_app", "0007_remove_imagem_imagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Desconto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Especificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aviso", models.TextField()),
                ("recomendacao", models.TextField()),
                ("restricao", models.TextField()),
                ("origem", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="produto",
            name="categoria",
        ),
        migrations.AddField(
            model_name="produto",
            name="data_cadastro",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="video",
            field=models.TextField(null=True),
        ),
    ]
